#!/bin/bash

# Get dotfiles installation directory
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

########################
# DOWNLOADS            #
########################

# Download tmux themepack
# assumes .tmux.conf already has themepack sourced
if [ ! -d "$HOME/.tmux-themepack" ]; then
  git clone https://github.com/jimeh/tmux-themepack.git
  mv tmux-themepack .tmux-themepack
fi

# Download zsh syntax hightlighting
# assumes plugin already added to .zshrc
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
  mv zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/
fi

# Install Firacode font
# assumes homebrew already installed
brew tap caskroom/fonts && brew cask install font-fira-code

########################
# SIMLINK CONFIG FILES #
########################

ln -sf "$DOTFILES_DIR/.gitconfig" ~
ln -sf "$DOTFILES_DIR/.tmux.conf" ~
ln -sf "$DOTFILES_DIR/.tmux-themepack" ~
ln -sf "$DOTFILES_DIR/.zshenv" ~
ln -sf "$DOTFILES_DIR/.zshrc" ~
ln -sf "$DOTFILES_DIR/.vimrc" ~

# Directory here is for "VSCode Insiders" edition
ln -sf "$DOTFILES_DIR/VSCode/settings.json" ~/Library/Application\ Support/Code\ -\ Insiders/User/
ln -sf "$DOTFILES_DIR/VSCode/keybindings.json" ~/Library/Application\ Support/Code\ -\ Insiders/User/

source ~/.zshrc
